// HOTMUM — the app shell. Vanilla, local-first, no framework, same as KILOS.
//
// Three screens: home, player, finish. The walk day is a player with one step.
//
// LOCAL-FIRST IS NOT NEGOTIABLE (CLAUDE.md): every write hits localStorage
// first so the loop never waits on a network. There is no sync yet — Season 01
// runs entirely on-device (PLAN.md §4).
//
// CRASH-SAFETY: the live session is persisted on every step change, every
// couple of seconds inside a step, and on pagehide/visibilitychange. A
// backgrounded tab or a mid-set refresh restores to the exact second.

import './style.css';
import { countdownTone, setAnnounce } from './cues.js';
import { demoFor, stillDemo } from './demos.js';
import {
  buildStepQueue,
  estimateSessionMins,
  nextWorkLabel,
  sessionOverview,
  tempoStateAt,
} from './engine.js';
import {
  formatLoad,
  getProfile,
  greeting,
  saveProfile,
  subGreeting,
} from './profile.js';
import {
  blockForDay,
  dayNumber,
  daysToGo,
  getMovement,
  getSession,
  HOTMUM_EXERCISES,
  HOTMUM_SESSIONS,
  hasKneeSwap,
  MOVEMENTS,
  SEASON,
  sessionForToday,
  sessionParts,
  tempoLabel,
  WALK,
} from './program.js';
import {
  buildShareData,
  renderShare,
  shareCanvas,
  TEMPLATES,
} from './share.js';
import {
  getSession as authSession,
  lastSynced,
  pendingSync,
  pullAndMerge,
  queuePush,
  signInWithPassword,
  signOut,
  signUpWithPassword,
  syncAvailable,
  syncOnStart,
} from './sync.js';
import {
  beep,
  hush,
  preload,
  resumeIfNeeded,
  setMuted,
  speak,
  speakAfter,
  unlock,
} from './voice.js';

// ─── Storage ───────────────────────────────────────────────────────────────

const K = {
  active: 'hotmum-active',
  history: 'hotmum-history',
  voice: 'hotmum-voice',
};
const get = (k, fallback = null) => {
  try {
    const raw = localStorage.getItem(k);
    return raw ? JSON.parse(raw) : fallback;
  } catch {
    return fallback;
  }
};
const set = (k, v) => {
  try {
    localStorage.setItem(k, JSON.stringify(v));
  } catch {
    /* private mode / quota — the session still runs, it just won't survive */
  }
};
const drop = (k) => {
  try {
    localStorage.removeItem(k);
  } catch {
    /* ignore */
  }
};

// LOCAL date, never toISOString(). In Manila (UTC+8) a 7am session stamped
// with the UTC date lands on YESTERDAY, so by that evening the app had
// forgotten she'd trained and invited her to do the session again.
const dayKey = (d = new Date()) =>
  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
const todayKey = () => dayKey();
const history = () => get(K.history, []);

// ─── One session, start to finish ──────────────────────────────────────────
// There used to be three cuts — FULL / SHORT / MINI — and the app offered to
// extend after the main work, because the first draft measured 41–46 minutes
// and asking a mother to commit to that at minute zero was the wrong question.
//
// Her rewrite fixed that at the source: a session is thirty minutes, and SHORT
// only saved eight of them. A choice that small isn't a mercy, it's a decision
// standing between her and starting. GO starts the session; the session ends
// when it ends. If thirty minutes isn't there today, ANOTHER MOVEMENT is one
// tap away and counts just the same.

// ─── A session is never used raw ───────────────────────────────────────────
// Two things happen to it first: `progress()` rewrites the work for the day
// of the 100 she's on, and EASY KNEE swaps the knee-dominant blocks out. Every
// caller goes through here so the sheet, the player, the estimate and the
// finish card can never disagree about what she actually did.

// `day` is PINNED on the run rather than read live: a session started at
// 11:55pm must not silently re-prescribe itself when the date rolls over
// mid-set. Everything that rebuilds the queue passes the run's own day back.
const prepped = (id, { easyKnee = false, day } = {}) =>
  sessionForToday(getSession(id), { easyKnee, day });
const runSession = () =>
  prepped(run.sessionId, { easyKnee: run.easyKnee, day: run.day });

// ─── Coach voice — Alice ───────────────────────────────────────────────────
// 44 clips in /voice-hotmum/, generated by scripts/generate-voice.mjs
// --pack hotmum. Every phrase resolves to <slug>.m4a; a missing clip fails
// once and is never retried, so a gap is silence rather than a stutter.
// iOS throttles speechSynthesis mid-session, so there is deliberately no TTS
// fallback — a phrase without a clip is simply not spoken.

// Voice used to live under its own key; the profile owns it now, and an
// existing hotmum-voice value is honoured once so nobody's setting flips.
let profile = getProfile();
const legacyVoice = get(K.voice);
if (legacyVoice !== null && legacyVoice !== undefined) {
  profile = saveProfile({ voice: legacyVoice });
  drop(K.voice);
}
let voiceOn = profile.voice;

// Alice speaks through voice.js (Web Audio), not <audio> elements — see the
// header there for why iOS clipped and dropped the old approach.

function say(slug) {
  if (voiceOn) speak(slug);
}
function sayAfter(slug) {
  if (voiceOn) speakAfter(slug);
}

// ─── Screen wake lock ──────────────────────────────────────────────────────
// A 50-second tempo set with no touches will sleep the screen mid-rep.

let wakeLock = null;
async function keepAwake(on) {
  try {
    if (on && !wakeLock && 'wakeLock' in navigator) {
      wakeLock = await navigator.wakeLock.request('screen');
      wakeLock.addEventListener('release', () => {
        wakeLock = null;
      });
    } else if (!on && wakeLock) {
      wakeLock.release();
      wakeLock = null;
    }
  } catch {
    /* denied or unsupported — not worth surfacing */
  }
}

// ─── App state ─────────────────────────────────────────────────────────────

const app = document.getElementById('app');
let view = 'home';
let run = null; // the live session
let raf = 0;
let lastBeat = '';
let lastSave = 0;

const esc = (s) =>
  String(s).replace(
    /[&<>"']/g,
    (c) =>
      ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[
        c
      ],
  );
const mmss = (secs) => {
  const s = Math.max(0, Math.ceil(Number(secs) || 0));
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
};
const exName = (id) => HOTMUM_EXERCISES[id]?.name || id;

// "Lower A" → "LOWER<br><em>A</em>". Escape FIRST, then add the markup —
// the other order escapes the tags we just wrote.
const dayTitle = (name) =>
  esc(name.toUpperCase()).replace(/ ([AB])$/, '<br><em>$1</em>');

// ─── Season ────────────────────────────────────────────────────────────────

// "27 Nov" — short enough to sit inside a line of copy.
const prettyDate = (iso) =>
  new Date(`${iso}T00:00:00`).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
  });

const RAIL_STEP = 5; // one bar per five days — twenty bars across the hundred
function seasonRail() {
  const at = Math.ceil(dayNumber() / RAIL_STEP);
  return Array.from({ length: SEASON.days / RAIL_STEP }, (_, i) => {
    const n = i + 1;
    return `<i class="${n < at ? 'on' : n === at ? 'now' : ''}"></i>`;
  }).join('');
}

// ─── No scoreboard ─────────────────────────────────────────────────────────
// The home screen used to carry a weekly target — "SESSIONS 2/3, WALKS 1/4".
// It's gone (2026-08-22). A weekly quota is a streak wearing a different hat:
// it turns a rearranged week into a visible deficit, and with a newborn every
// week gets rearranged. The hundred days already do the motivating, and they
// do it without ever showing her a number she's behind on.

function doneToday() {
  const t = todayKey();
  return history().some((h) => h.date === t);
}

// ─── Nav ───────────────────────────────────────────────────────────────────
// Three tabs, same shape as KILOS. Hidden during the player and the finish
// card — mid-set is not a moment to offer navigation.

const TABS = [
  { id: 'home', label: 'Today' },
  { id: 'program', label: 'Program' },
  { id: 'athlete', label: 'Me' },
];

function nav(active) {
  return `<nav class="nav">${TABS.map(
    (t) =>
      `<button class="nav-btn" data-go="${t.id}" aria-current="${t.id === active}">${t.label}</button>`,
  ).join('')}</nav>`;
}

function wireNav() {
  for (const b of app.querySelectorAll('[data-go]')) {
    b.addEventListener('click', () => go(b.dataset.go));
  }
}

function go(where) {
  view = where;
  if (where === 'home') renderHome();
  else if (where === 'program') renderProgram();
  else if (where === 'athlete') renderAthlete();
}

// ─── Program ───────────────────────────────────────────────────────────────
// What she'd otherwise only discover by doing it: the whole season, every
// session, and every movement's coaching copy — which until now surfaced one
// line at a time, mid-set, when it is far too late to read it.

function renderProgram() {
  const day = dayNumber();
  const current = blockForDay(day);

  const blocks = SEASON.blocks
    .map((b) => {
      const on = b === current;
      return `<div class="row ${on ? 'row-on' : ''}">
        <div>
          <div class="row-t">${esc(b.name)}</div>
          <div class="row-s">${esc(b.blurb)}</div>
        </div>
        <span class="lbl lbl-sm ${on ? 'lbl-hot' : ''}">DAY ${b.days[0]}–${b.days[1]}</span>
      </div>`;
    })
    .join('');

  const sessions = HOTMUM_SESSIONS.map((s) => {
    const p = prepped(s.id, { day });
    return `<button class="row row-tap" data-open="${esc(s.id)}">
      <div>
        <div class="row-t">${esc(s.day)} · ${esc(s.sub.toUpperCase())}</div>
        <div class="row-s">${esc(s.blurb)}</div>
      </div>
      <span class="lbl lbl-sm lbl-hot">${estimateSessionMins(p)} MIN</span>
    </button>`;
  }).join('');

  const moves = MOVEMENTS.map(
    (m) => `<div class="row">
      <div>
        <div class="row-t">${esc(m.name)}</div>
        <div class="row-s">${esc(m.blurb)}</div>
      </div>
      <span class="lbl lbl-sm">${m.mins} MIN</span>
    </div>`,
  ).join('');

  app.innerHTML = `
    <div class="screen has-nav scr-program">
      <div class="top">
        <div>
          <div class="lbl lbl-sm">${esc(SEASON.label)}</div>
          <h1 class="page-h">${esc(SEASON.name)}</h1>
        </div>
      </div>
      <div class="season-row">
        <span class="lbl lbl-sm">DAY ${day} OF ${SEASON.days} · ${esc(current.name)}</span>
        <span class="lbl lbl-sm lbl-hot">${daysToGo()} LEFT</span>
      </div>
      <div class="season">${seasonRail()}</div>
      <p class="fine">${SEASON.days} days, ${prettyDate(SEASON.startDate)} to
        ${prettyDate(SEASON.endDate)}. Thirty minutes of movement on every one
        of them.</p>

      <div class="pane pane-a">
        <h2 class="sec-h">The five blocks</h2>
        ${blocks}
      </div>

      <div class="pane pane-b">
        <h2 class="sec-h">The three sessions</h2>
        ${sessions}
      </div>

      <div class="pane pane-c">
        <h2 class="sec-h">The other four days</h2>
        <p class="row-s">Every day is thirty minutes of movement. On a day
          you're not lifting — or not home — any of these counts.</p>
        ${moves}
      </div>
      <p class="fine pane-wide">Every set is a countdown, not a count — Alice
        speaks the tempo and calls the reps, so you never have to keep track.</p>
    </div>
    ${nav('program')}`;

  wireNav();
  for (const b of app.querySelectorAll('[data-ex]')) {
    b.addEventListener('click', () => openExercise(b.dataset.ex));
  }
  for (const b of app.querySelectorAll('[data-open]')) {
    b.addEventListener('click', () => openSession(b.dataset.open));
  }
}

// A movement's full coaching copy, on demand.
function openExercise(id) {
  const ex = HOTMUM_EXERCISES[id];
  if (!ex) return;
  const tempo = ex.repTempo ? tempoLabel(ex.repTempo) : null;
  const sheet = document.createElement('div');
  sheet.className = 'sheet';
  sheet.innerHTML = `<div class="sheet-card" role="dialog" aria-label="${esc(ex.name)}">
      <div class="sheet-top">
        <h3>${esc(ex.name)}</h3>
        <button class="icon-btn" id="sheet-x" aria-label="Close">✕</button>
      </div>
      <div class="hm-demo ex-demo">${demoFor(id)}</div>
      ${tempo ? `<span class="lbl lbl-sm lbl-hot">TEMPO ${esc(tempo)}</span>` : ''}
      <dl class="sheet-dl">
        <dt>How to</dt><dd>${esc(ex.cue)}</dd>
        <dt>Should feel like</dt><dd>${esc(ex.feel)}</dd>
        <dt>Watch out for</dt><dd>${esc(ex.avoid)}</dd>
        ${ex.knee ? `<dt class="dt-knee">Your knee</dt><dd>${esc(ex.knee)}</dd>` : ''}
        <dt>Why it's in here</dt><dd>${esc(ex.why)}</dd>
      </dl>
    </div>`;
  const close = () => sheet.remove();
  sheet.addEventListener('click', (e) => {
    if (e.target === sheet || e.target.id === 'sheet-x') close();
  });
  document.body.appendChild(sheet);
}

// ─── Share ─────────────────────────────────────────────────────────────────
// Three cards that read as one set (share.js). Opened from the finish card and
// from the athlete page, so she can post the day she had or just the mark.

function shareDataFor(record) {
  // Sharing from the athlete page has no record. There's no schedule to fall
  // back on any more, so it takes the LAST thing she actually did — a fact
  // rather than a guess about what today was meant to be.
  const last = [...history()].reverse()[0] || null;
  const src = record || last;
  const session = src?.sessionId ? getSession(src.sessionId) : null;
  const kind = src?.kind || 'session';
  const base = record || (last ? { ...last } : { kind });
  return buildShareData({
    record:
      base.kind === 'walk'
        ? { ...base, moveName: getMovement(base.moveId).name }
        : base,
    session,
    day: dayNumber(),
    days: SEASON.days,
    daysToGo: daysToGo(),
    seasonLabel: SEASON.label,
    seasonName: SEASON.name,
    rows: session
      ? sessionOverview(session).map((r) => ({
          title: r.title,
          detail: r.detail,
        }))
      : [],
  });
}

function openShare(record) {
  const data = shareDataFor(record);
  // The workout card needs a workout; offer it only when there is one.
  const templates = data.rows.length
    ? TEMPLATES
    : TEMPLATES.filter((t) => t.id !== 'workout');
  let pick = templates[0].id;

  const sheet = document.createElement('div');
  sheet.className = 'sheet';
  sheet.innerHTML = `<div class="sheet-card" role="dialog" aria-label="Share">
      <div class="sheet-top"><h3>Share</h3>
        <button class="icon-btn" id="sheet-x" aria-label="Close">✕</button></div>
      <div class="tpl-row">${templates
        .map(
          (t) =>
            `<button class="tpl" data-tpl="${t.id}" aria-pressed="${t.id === pick}">${esc(t.name)}</button>`,
        )
        .join('')}</div>
      <canvas class="tpl-preview" id="share-canvas"></canvas>
      <button class="btn" id="share-go">SAVE / SHARE</button>
    </div>`;
  document.body.appendChild(sheet);

  const canvas = sheet.querySelector('#share-canvas');
  const paint = () => renderShare(canvas, data, pick);
  paint();

  for (const b of sheet.querySelectorAll('[data-tpl]')) {
    b.addEventListener('click', () => {
      pick = b.dataset.tpl;
      for (const o of sheet.querySelectorAll('[data-tpl]'))
        o.setAttribute('aria-pressed', String(o === b));
      paint();
    });
  }
  sheet.querySelector('#share-go').addEventListener('click', async () => {
    await shareCanvas(canvas, `hotmum-${pick}.png`);
  });
  sheet.addEventListener('click', (e) => {
    if (e.target === sheet || e.target.id === 'sheet-x') sheet.remove();
  });
}

// ─── Account ───────────────────────────────────────────────────────────────
// Her own login on the shared Supabase project, so a lost or replaced phone
// doesn't lose the season. Everything still works signed out — this is backup,
// not a gate (CLAUDE.md: never paywall or block a basic need).

let account = null; // cached session, refreshed on render

async function accountSection() {
  if (!syncAvailable()) {
    return `<p class="fine">Cloud backup isn't configured on this build —
      everything is saved on this phone.</p>`;
  }
  account = await authSession();
  if (!account) {
    return `<button class="row row-tap" id="btn-account">
      <div><div class="row-t">Back up my progress</div>
        <div class="row-s">Create a login so a new phone keeps the season</div></div>
      <span class="lbl lbl-sm lbl-hot">SET UP</span>
    </button>`;
  }
  const when = lastSynced();
  const ago = when
    ? `${Math.max(1, Math.round((Date.now() - when) / 60000))} min ago`
    : 'not yet';
  return `<div class="row">
      <div><div class="row-t">${esc(account.user.user_metadata?.username || 'Signed in')}</div>
        <div class="row-s">${pendingSync() ? 'Waiting for signal…' : `Backed up ${esc(ago)}`}</div></div>
      <button class="lbl lbl-sm lbl-hot del-txt" id="btn-signout">SIGN OUT</button>
    </div>`;
}

function openAccount({ firstRun = false } = {}) {
  const sheet = document.createElement('div');
  sheet.className = 'sheet';
  sheet.innerHTML = `<div class="sheet-card" role="dialog" aria-label="Back up my progress">
      <div class="sheet-top"><h3>${firstRun ? 'Before you start' : 'Back up my progress'}</h3>
        <button class="icon-btn" id="sheet-x" aria-label="Close">✕</button></div>
      <p class="row-s">${
        firstRun
          ? 'Make a login so twenty weeks of work survives a lost or replaced phone. It takes ten seconds, and you can do it later from Me.'
          : 'A username and password, just for you. It keeps the season if this phone is lost or replaced. Nothing is shared.'
      }</p>
      <input class="text-input" id="ac-user" placeholder="username" autocapitalize="none" autocomplete="username" />
      <input class="text-input" id="ac-pass" type="password" placeholder="password" autocomplete="current-password" />
      <p class="fine" id="ac-msg"></p>
      <button class="btn" id="ac-create">CREATE</button>
      <div class="btn-row">
        <button class="btn btn-ghost btn-sm" id="ac-signin">I ALREADY HAVE ONE</button>
        ${firstRun ? '<button class="btn btn-ghost btn-sm" id="ac-later">NOT NOW</button>' : ''}
      </div>
    </div>`;
  document.body.appendChild(sheet);
  const msg = sheet.querySelector('#ac-msg');
  const creds = () => [
    sheet.querySelector('#ac-user').value.trim(),
    sheet.querySelector('#ac-pass').value,
  ];

  const done = async (fn, label) => {
    const [u, p] = creds();
    if (!u || p.length < 6) {
      msg.textContent = 'A username and at least 6 characters.';
      return;
    }
    msg.textContent = `${label}…`;
    const { error } = await fn(u, p);
    if (error) {
      msg.textContent = error.message;
      return;
    }
    await pullAndMerge();
    sheet.remove();
    renderAthlete();
  };

  sheet
    .querySelector('#ac-create')
    .addEventListener('click', () =>
      done((u, p) => signUpWithPassword(u, u, p), 'Creating'),
    );
  sheet
    .querySelector('#ac-signin')
    .addEventListener('click', () =>
      done((u, p) => signInWithPassword(u, p), 'Signing in'),
    );
  sheet
    .querySelector('#ac-later')
    ?.addEventListener('click', () => sheet.remove());
  sheet.addEventListener('click', (e) => {
    if (e.target === sheet || e.target.id === 'sheet-x') sheet.remove();
  });
}

// Offered on EVERY cold start until she actually has an account — twenty weeks
// of work living on one phone with no backup is the thing worth being
// persistent about. Still skippable every time: NOT NOW always works, and it
// never interrupts a session, only a fresh open.
async function offerBackup() {
  if (!syncAvailable()) return;
  if (await authSession()) return; // signed in — never ask again
  openAccount({ firstRun: true });
}

// ─── Athlete ───────────────────────────────────────────────────────────────

function renderAthlete() {
  const hist = history();
  const sessions = hist.filter((h) => h.kind === 'session');
  const walks = hist.filter((h) => h.kind === 'walk');
  const totalSecs = hist.reduce((n, h) => n + (h.secs || 0), 0);
  const totalTut = hist.reduce((n, h) => n + (h.tut || 0), 0);

  const log = hist
    .slice()
    .reverse()
    .slice(0, 40)
    .map((h, i) => {
      const s = h.sessionId ? getSession(h.sessionId) : null;
      const title = s ? s.name : 'Walk';
      const detail = s
        ? `${h.sets} sets · ${mmss(h.secs)}`
        : `${WALK.mins} min`;
      return `<div class="row">
        <div>
          <div class="row-t">${esc(title)}</div>
          <div class="row-s">${esc(h.date)} · ${esc(detail)}</div>
        </div>
        <button class="del" data-del="${hist.length - 1 - i}" aria-label="Delete this entry">✕</button>
      </div>`;
    })
    .join('');

  app.innerHTML = `
    <div class="screen has-nav scr-me">
      <div class="top">
        <div>
          <div class="lbl lbl-sm">ATHLETE</div>
          <h1 class="page-h">${esc(profile.name)}</h1>
        </div>
      </div>

      <div class="pane pane-a">
      <h2 class="sec-h">This season</h2>
      <div class="tiles">
        <div class="tile"><b>${sessions.length}</b><span class="lbl lbl-sm">SESSIONS</span></div>
        <div class="tile"><b>${walks.length}</b><span class="lbl lbl-sm">WALKS</span></div>
        <div class="tile"><b>${Math.round(totalSecs / 60)}</b><span class="lbl lbl-sm">MINUTES</span></div>
        <div class="tile"><b>${Math.round(totalTut / 60)}</b><span class="lbl lbl-sm">UNDER TENSION</span></div>
      </div>
      </div>

      <div class="pane pane-b">
      <h2 class="sec-h">Settings</h2>
      <button class="row row-tap" data-edit="name">
        <div><div class="row-t">Name</div><div class="row-s">Used in the greeting</div></div>
        <span class="lbl lbl-sm lbl-hot">${esc(profile.name)}</span>
      </button>
      <button class="row row-tap" data-edit="unit">
        <div><div class="row-t">Weight unit</div><div class="row-s">Display only — the program stays in pounds</div></div>
        <span class="lbl lbl-sm lbl-hot">${esc(profile.unit.toUpperCase())}</span>
      </button>
      <button class="row row-tap" data-edit="voice">
        <div><div class="row-t">Coach voice</div><div class="row-s">Alice calls the tempo and the reps</div></div>
        <span class="lbl lbl-sm lbl-hot">${voiceOn ? 'ON' : 'OFF'}</span>
      </button>

      <button class="row row-tap" id="share-mark">
        <div><div class="row-t">Share a card</div><div class="row-s">The countdown, or just the mark</div></div>
        <span class="lbl lbl-sm lbl-hot">↗</span>
      </button>

      <h2 class="sec-h">Backup</h2>
      <div id="account-slot"><p class="fine">Checking…</p></div>

      <h2 class="sec-h">About</h2>
      <button class="row row-tap" id="btn-update">
        <div><div class="row-t">Check for update</div><div class="row-s" id="update-s">Get the newest version</div></div>
        <span class="lbl lbl-sm lbl-hot">↻</span>
      </button>
      <p class="fine" id="build-stamp"></p>
      <p class="fine">HOTMUM — hot as in strong.<br>Everything lives on this phone. Nothing is uploaded.</p>
      </div>

      <div class="pane pane-c">
      <h2 class="sec-h">The log</h2>
      ${log || '<p class="fine">Nothing logged yet. It starts on your first session.</p>'}
      </div>
    </div>
    ${nav('athlete')}`;

  wireNav();
  const stamp = app.querySelector('#build-stamp');
  if (stamp) {
    stamp.textContent = `Version ${import.meta.env.KILOS_BUILD || 'dev'} · ${import.meta.env.KILOS_COMMIT || '—'}`;
  }
  for (const b of app.querySelectorAll('[data-edit]')) {
    b.addEventListener('click', () => editSetting(b.dataset.edit));
  }
  for (const b of app.querySelectorAll('[data-del]')) {
    b.addEventListener('click', () => {
      const list = history();
      list.splice(Number(b.dataset.del), 1);
      set(K.history, list);
      renderAthlete();
    });
  }
  app.querySelector('#btn-update')?.addEventListener('click', checkForUpdate);
  app
    .querySelector('#share-mark')
    ?.addEventListener('click', () => openShare(null));

  // Painted in after the page: checking the session is a network call and the
  // rest of the screen shouldn't wait on it.
  accountSection().then((html) => {
    const slot = app.querySelector('#account-slot');
    if (!slot) return; // she navigated away while we were checking
    slot.innerHTML = html;
    slot.querySelector('#btn-account')?.addEventListener('click', openAccount);
    slot.querySelector('#btn-signout')?.addEventListener('click', async () => {
      await signOut();
      renderAthlete();
    });
  });
}

// Tap a settings row to change it — inline, no separate settings screen.
function editSetting(field) {
  if (field === 'unit') {
    profile = saveProfile({ unit: profile.unit === 'lb' ? 'kg' : 'lb' });
    return renderAthlete();
  }
  if (field === 'voice') {
    voiceOn = !voiceOn;
    setMuted(!voiceOn);
    profile = saveProfile({ voice: voiceOn });
    if (voiceOn) {
      unlock().then(() => say('go'));
    }
    return renderAthlete();
  }
  if (field === 'name') {
    const sheet = document.createElement('div');
    sheet.className = 'sheet';
    sheet.innerHTML = `<div class="sheet-card" role="dialog" aria-label="Your name">
        <div class="sheet-top"><h3>Your name</h3>
          <button class="icon-btn" id="sheet-x" aria-label="Close">✕</button></div>
        <p class="row-s">However you'd like to be greeted.</p>
        <input class="text-input" id="name-in" value="${esc(profile.name)}" maxlength="24" autocomplete="off" />
        <button class="btn" id="name-save">SAVE</button>
      </div>`;
    document.body.appendChild(sheet);
    const input = sheet.querySelector('#name-in');
    input.focus();
    input.select();
    const save = () => {
      const v = input.value.trim();
      if (v) profile = saveProfile({ name: v });
      sheet.remove();
      renderAthlete();
    };
    sheet.querySelector('#name-save').addEventListener('click', save);
    input.addEventListener('keydown', (e) => e.key === 'Enter' && save());
    sheet.addEventListener('click', (e) => {
      if (e.target === sheet || e.target.id === 'sheet-x') sheet.remove();
    });
  }
}

// ─── Updates ───────────────────────────────────────────────────────────────
// The service worker installs a new build and then SITS IN `waiting` forever.
// It only steps aside when something posts it {type:'SKIP_WAITING'} — the
// listener is right there in the generated sw.js and nothing was ever sending
// the message. So every new deploy installed, waited, and never took over;
// pressing "check for update" found the update, reloaded, and the OLD worker
// served the OLD html from its own precache. Hence: same version, every time.
//
// This is the standard dance: wait for the incoming worker to finish
// installing, tell it to skip waiting, wait for it to actually take control,
// and only then reload.

function applyWaitingWorker(worker) {
  return new Promise((resolve) => {
    const takeOver = () => {
      navigator.serviceWorker.addEventListener(
        'controllerchange',
        () => resolve(true),
        { once: true },
      );
      worker.postMessage({ type: 'SKIP_WAITING' });
    };
    if (worker.state === 'installed') takeOver();
    else {
      worker.addEventListener('statechange', () => {
        if (worker.state === 'installed') takeOver();
        else if (worker.state === 'redundant') resolve(false);
      });
    }
    setTimeout(() => resolve(false), 15000); // never hang on a stalled install
  });
}

async function checkForUpdate() {
  const say = (t) => {
    const el = app.querySelector('#update-s');
    if (el) el.textContent = t;
  };
  say('Checking…');
  try {
    const reg = await navigator.serviceWorker?.getRegistration();
    if (!reg) {
      say('Not installed yet — add it to your Home Screen first.');
      return;
    }
    await reg.update();
    const incoming = reg.waiting || reg.installing;
    if (!incoming) {
      say("You're on the newest version.");
      return;
    }
    say('New version found — updating…');
    const ok = await applyWaitingWorker(incoming);
    if (ok) location.reload();
    else say('Update stalled. Close the app fully and reopen it.');
  } catch {
    say('Could not check — try again when you have signal.');
  }
}

// Take a pending update on a cold open, so she never has to think about it —
// but NEVER mid-session: reloading someone out of a set is unforgivable.
// Once per tab, so a broken install can't put her in a reload loop.
async function autoApplyUpdate() {
  if (run || sessionStorage.getItem('hotmum-updated')) return;
  try {
    const reg = await navigator.serviceWorker?.getRegistration();
    const waiting = reg?.waiting;
    if (!waiting) return;
    sessionStorage.setItem('hotmum-updated', '1');
    if (await applyWaitingWorker(waiting)) location.reload();
  } catch {
    /* an update that won't apply is not worth interrupting her for */
  }
}

// ─── Home ──────────────────────────────────────────────────────────────────
// ─── Home ──────────────────────────────────────────────────────────────────
// KILOS' shape: wordmark, greeting, a grid of boxes, then a card you tap to
// open the day. Hers counts boxes across the hundred rather than days in a
// month — the season IS the motivation, so it's the thing the page is mostly
// made of.

const DAY_MS = 86400000;

// ONE BOX PER DAY OF THE HUNDRED. Filled when something was logged, marked on
// today, dim once it's behind her. A missed day just stays empty — no red, no
// broken streak, nothing to feel bad about. That's the whole reason the season
// replaced streaks: with a newborn, a missed day is information, not a failure.
function hundredGrid() {
  const start = new Date(`${SEASON.startDate}T00:00:00`);
  const today = todayKey();
  const done = new Set(history().map((h) => h.date));

  const cells = [];
  let filled = 0;
  for (let i = 0; i < SEASON.days; i++) {
    const k = dayKey(new Date(start.getTime() + i * DAY_MS));
    let cls = '';
    if (done.has(k)) {
      cls = 'done';
      filled++;
    } else if (k === today) cls = 'today';
    else if (k < today) cls = 'past';
    cells.push(`<i class="bx ${cls}"></i>`);
  }
  return { html: cells.join(''), filled, total: SEASON.days };
}

function renderHome() {
  const day = dayNumber();
  const block = blockForDay(day);
  const done = doneToday();
  const grid = hundredGrid();
  const hist = history();

  const recent = hist
    .slice(-3)
    .reverse()
    .map((h) => {
      const s = h.sessionId ? getSession(h.sessionId) : null;
      return `<div class="wk">
        <span class="nm">${esc(s ? s.name : getMovement(h.moveId).name)}</span>
        <span class="lbl lbl-sm">${esc(h.date)}</span>
      </div>`;
    })
    .join('');

  const card = `<button class="today-card" id="open-today">
      <div>
        <span class="lbl lbl-sm">TODAY</span>
        <div class="day-name">${
          done ? 'ANYTHING<br><em>ELSE?</em>' : 'WHAT ARE<br>WE <em>DOING?</em>'
        }</div>
        <div class="row-s">${
          done
            ? 'One more if you want it — a walk always counts.'
            : 'Thirty minutes, whatever shape it takes.'
        }</div>
      </div>
      <span class="chev">→</span>
    </button>`;

  app.innerHTML = `
    <div class="screen has-nav scr-home">
      <div class="top">
        <div class="mark">HOT<br>MUM</div>
        <button class="icon-btn voice-btn${voiceOn ? '' : ' muted'}" id="voice" aria-pressed="${voiceOn}" aria-label="Coach voice">♪</button>
      </div>

      <div class="pane pane-a">
        <div class="hello">
          <h1 class="page-h">${esc(greeting(profile.name, new Date(), done))}</h1>
          <p class="row-s">${esc(subGreeting({ doneToday: done, day, days: SEASON.days }))}</p>
        </div>
      </div>

      <div class="pane pane-b">
        <div class="season-row">
          <span class="lbl lbl-sm">DAY ${day} OF ${SEASON.days} · ${esc(block.name)}</span>
          <span class="lbl lbl-sm lbl-hot">${daysToGo()} LEFT</span>
        </div>
        <div class="boxes">${grid.html}</div>
        <div class="season-row boxes-key">
          <span class="lbl lbl-sm">${grid.filled} DAYS SHOWED UP</span>
          <span class="lbl lbl-sm">DAY ${SEASON.days} →</span>
        </div>
      </div>

      <div class="pane pane-c">
        ${card}
        ${recent ? `<h2 class="sec-h">Recent</h2>${recent}` : ''}
        <p class="fine">Everything lives on this phone.</p>
      </div>
    </div>
    ${nav('home')}`;

  wireNav();
  app.querySelector('#voice')?.addEventListener('click', () => {
    voiceOn = !voiceOn;
    setMuted(!voiceOn);
    profile = saveProfile({ voice: voiceOn });
    renderHome();
  });
  app.querySelector('#open-today')?.addEventListener('click', openPicker);
}

// ─── She picks the day ─────────────────────────────────────────────────────
// There is no schedule. All three sessions and the walk are always available,
// and the home card asks rather than tells — a fixed Mon/Wed/Fri turns every
// rearranged day into a missed one, which is the wrong feeling to build into
// an app used by someone with a newborn.
//
// The only guidance offered is FACT, not instruction: how long ago she last
// did each one. That helps her balance without telling her she's behind.

function lastDoneLabel(match) {
  const hits = history().filter(match);
  if (!hits.length) return 'not yet';
  const last = hits[hits.length - 1];
  const days = Math.round(
    (new Date(`${todayKey()}T00:00:00`) - new Date(`${last.date}T00:00:00`)) /
      DAY_MS,
  );
  if (days <= 0) return 'today';
  if (days === 1) return 'yesterday';
  return `${days} days ago`;
}

function openPicker() {
  const options = [
    ...HOTMUM_SESSIONS.map((s) => ({
      id: s.id,
      name: `${s.day} · ${s.sub.toUpperCase()}`,
      sub: s.blurb,
      meta: `${estimateSessionMins(prepped(s.id))} MIN`,
      last: lastDoneLabel((h) => h.sessionId === s.id),
    })),
    {
      id: 'walk',
      name: 'WALK',
      sub: WALK.blurb,
      meta: `${WALK.mins} MIN`,
      // Legacy records have no moveId — they were all walks.
      last: lastDoneLabel(
        (h) => h.kind === 'walk' && (!h.moveId || h.moveId === 'walk'),
      ),
    },
    {
      id: 'another',
      name: 'ANOTHER MOVEMENT',
      sub: 'Yoga, Pilates, a stretch — or whatever you actually did.',
      meta: 'ANY',
      last: lastDoneLabel(
        (h) => h.kind === 'walk' && h.moveId && h.moveId !== 'walk',
      ),
    },
  ];

  const sheet = document.createElement('div');
  sheet.className = 'sheet';
  sheet.innerHTML = `<div class="sheet-card" role="dialog" aria-label="What are we doing today?">
      <div class="sheet-top">
        <h3>What are we doing?</h3>
        <button class="icon-btn" id="sheet-x" aria-label="Close">✕</button>
      </div>
      <p class="row-s">Your pick — there's no wrong one.</p>
      ${options
        .map(
          (o) => `<button class="row row-tap pick" data-pick="${esc(o.id)}">
            <div>
              <div class="row-t">${esc(o.name)}</div>
              <div class="row-s">${esc(o.sub)}</div>
            </div>
            <span class="pick-meta">
              <span class="lbl lbl-sm lbl-hot">${esc(o.meta)}</span>
              <span class="lbl lbl-sm">${esc(o.last)}</span>
            </span>
          </button>`,
        )
        .join('')}
    </div>`;
  document.body.appendChild(sheet);

  for (const b of sheet.querySelectorAll('[data-pick]')) {
    b.addEventListener('click', () => {
      sheet.remove();
      openSession(b.dataset.pick);
    });
  }
  sheet.addEventListener('click', (e) => {
    if (e.target === sheet || e.target.id === 'sheet-x') sheet.remove();
  });
}

// ─── Open a day, then go ───────────────────────────────────────────────────
// A SHEET, not a page and not an accordion: it opens over whatever she was
// looking at, scrolls inside itself if the movement list is long, and closes
// back to exactly where she was. Same on a phone and a laptop — no scrolling
// down to find the button.

function openSession(id) {
  if (id === 'walk') return openMoveSheet('walk');
  if (id === 'another') return openMovePicker();
  if (!getSession(id)) return;

  // EASY KNEE lives on the sheet, not in settings: the answer changes day to
  // day, and the moment she has to decide is the moment she opens the session.
  let easyKnee = false;

  const sheet = document.createElement('div');
  sheet.className = 'sheet';
  document.body.appendChild(sheet);

  function paint() {
    const s = prepped(id, { easyKnee });
    const mins = estimateSessionMins(s);
    // The list is grouped by the session's own names for its parts. Those
    // labels used to be the "add the knee work?" prompts; with one whole
    // session there's nothing to prompt, but the structure is still the thing
    // her plan is organised around, so it becomes the shape of the list.
    const overview = sessionOverview(s);
    const rowFor = (b) => {
      const r = overview[s.blocks.indexOf(b)];
      const load = b.load ? formatLoad(b.load, profile.unit) : '';
      return `<button class="ex-row${b.swappedFrom ? ' ex-swapped' : ''}" data-ex="${esc(b.ex)}">
        <span class="ex-fig">${stillDemo(b.ex)}</span>
        <span class="ex-txt">
          <span class="ex-nm">${esc(r.title)}</span>
          <span class="ex-d">${esc(r.detail)}${load ? ` · ${esc(load)}` : ''}</span>
        </span>
      </button>`;
    };
    const rows = sessionParts(s)
      .map(
        (part) =>
          `<div class="part-h"><span class="lbl lbl-sm">${esc(part.label)}</span></div>${part.blocks.map(rowFor).join('')}`,
      )
      .join('');

    sheet.innerHTML = `<div class="sheet-card sheet-session" role="dialog" aria-label="${esc(s.name)}">
      <div class="sheet-top">
        <div>
          <span class="lbl lbl-sm">DAY ${dayNumber()} OF ${SEASON.days} · ${esc(blockForDay(dayNumber()).name)}</span>
          <h3 class="sheet-day">${dayTitle(s.sub)}</h3>
        </div>
        <button class="icon-btn" id="sheet-x" aria-label="Close">✕</button>
      </div>
      <p class="row-s">${esc(s.blurb)}</p>
      ${
        hasKneeSwap(getSession(id))
          ? `<button class="knee-toggle" id="knee" aria-pressed="${easyKnee}">
              <span class="knee-t">EASY ON THE KNEE</span>
              <span class="knee-s">${
                easyKnee
                  ? 'Squats and lunges swapped for hip work. The wall sit stays — holds help.'
                  : 'Knee sore today? Swap the squats and lunges for hip work.'
              }</span>
              <span class="knee-sw" aria-hidden="true"></span>
            </button>`
          : ''
      }
      <div class="sheet-scroll">${rows}</div>
      <button class="btn" id="go-session">GO<i>${mins} MIN</i></button>
      <button class="btn-quiet" id="another">Another movement →</button>
    </div>`;

    for (const b of sheet.querySelectorAll('[data-ex]')) {
      b.addEventListener('click', () => openExercise(b.dataset.ex));
    }
    sheet.querySelector('#knee')?.addEventListener('click', () => {
      easyKnee = !easyKnee;
      paint();
    });
    sheet.querySelector('#another').addEventListener('click', () => {
      sheet.remove();
      openMovePicker();
    });
    sheet.querySelector('#go-session').addEventListener('click', () => {
      unlock(); // MUST be inside the tap — iOS only lets a gesture start audio
      sheet.remove();
      startSession(id, easyKnee);
    });
  }

  paint();
  sheet.addEventListener('click', (e) => {
    if (e.target === sheet || e.target.id === 'sheet-x') sheet.remove();
  });
}

// ─── Another movement ──────────────────────────────────────────────────────
// The button that saves the day she isn't home, or the day her knee says no.
// Everything in here counts as showing up: the season is a hundred days of
// MOVEMENT, and an app that only credits its own sessions would quietly teach
// her that a morning at her mum's with a walk in it was a failure.

function openMovePicker() {
  const sheet = document.createElement('div');
  sheet.className = 'sheet';
  sheet.innerHTML = `<div class="sheet-card" role="dialog" aria-label="Another movement">
      <div class="sheet-top">
        <h3>Another movement</h3>
        <button class="icon-btn" id="sheet-x" aria-label="Close">✕</button>
      </div>
      <p class="row-s">Not at home, or not today? All of it counts.</p>
      ${MOVEMENTS.map(
        (m) => `<button class="row row-tap" data-move="${esc(m.id)}">
          <div>
            <div class="row-t">${esc(m.name.toUpperCase())}</div>
            <div class="row-s">${esc(m.blurb)}</div>
          </div>
          <span class="pick-meta">
            <span class="lbl lbl-sm lbl-hot">${m.mins} MIN</span>
            <span class="lbl lbl-sm">${esc(lastDoneLabel((h) => h.moveId === m.id))}</span>
          </span>
        </button>`,
      ).join('')}
    </div>`;
  document.body.appendChild(sheet);
  for (const b of sheet.querySelectorAll('[data-move]')) {
    b.addEventListener('click', () => {
      sheet.remove();
      openMoveSheet(b.dataset.move);
    });
  }
  sheet.addEventListener('click', (e) => {
    if (e.target === sheet || e.target.id === 'sheet-x') sheet.remove();
  });
}

function openMoveSheet(id) {
  const move = getMovement(id);
  const sheet = document.createElement('div');
  sheet.className = 'sheet';
  sheet.innerHTML = `<div class="sheet-card" role="dialog" aria-label="${esc(move.name)}">
      <div class="sheet-top">
        <div>
          <span class="lbl lbl-sm">DAY ${dayNumber()} OF ${SEASON.days}</span>
          <h3 class="sheet-day">${dayTitle(move.name)}</h3>
        </div>
        <button class="icon-btn" id="sheet-x" aria-label="Close">✕</button>
      </div>
      <p class="row-s">${esc(move.blurb)}</p>
      <div class="stats">
        <div class="stat"><b>${move.mins}</b><span class="lbl lbl-sm">MINUTES</span></div>
        <div class="stat"><b>${history().filter((h) => h.kind === 'walk').length}</b><span class="lbl lbl-sm">LOGGED</span></div>
      </div>
      <button class="btn" id="go-move">START</button>
      <div class="btn-row"><button class="btn btn-ghost btn-sm" id="log-move">ALREADY DID IT — LOG IT</button></div>
    </div>`;
  document.body.appendChild(sheet);
  sheet.querySelector('#go-move').addEventListener('click', () => {
    unlock();
    sheet.remove();
    startMove(id);
  });
  sheet.querySelector('#log-move').addEventListener('click', () => {
    const rec = { kind: 'walk', moveId: id, secs: move.mins * 60 };
    logDone(rec);
    sheet.remove();
    renderFinish(rec);
  });
  sheet.addEventListener('click', (e) => {
    if (e.target === sheet || e.target.id === 'sheet-x') sheet.remove();
  });
}

// ─── Starting work ─────────────────────────────────────────────────────────

function startSession(sessionId, easyKnee = false) {
  const day = dayNumber();
  const session = prepped(sessionId, { easyKnee, day });
  run = {
    kind: 'session',
    sessionId,
    easyKnee,
    day,
    queue: buildStepQueue(session),
    idx: 0,
    elapsed: 0,
    running: true,
    since: Date.now(),
    totals: { secs: 0, sets: 0, tut: 0 },
    deltas: [],
    startedAt: Date.now(),
  };
  enterPlayer();
}

// Split from startMove so restore() can rebuild a paused movement WITHOUT
// entering the player — it entered twice otherwise, announcing "go" and
// preloading the whole vocabulary two times over.
//
// Every movement is stored with kind 'walk'. That's deliberate: the weekly
// target, the sync dedup key and two years of her history all count walks, and
// a yoga day that didn't count as showing up would be a worse bug than an
// imprecise field name. `moveId` carries which one it was.
function buildWalkRun(moveId = 'walk') {
  const move = getMovement(moveId);
  run = {
    kind: 'walk',
    moveId: move.id,
    queue: [
      {
        kind: 'work',
        exId: 'walk',
        secs: move.mins * 60,
        phase: move.name.toUpperCase(),
        meta: `${move.mins} MINUTES`,
      },
    ],
    idx: 0,
    elapsed: 0,
    running: true,
    since: Date.now(),
    totals: { secs: 0, sets: 0, tut: 0 },
    deltas: [],
    startedAt: Date.now(),
  };
}

function startMove(moveId = 'walk') {
  buildWalkRun(moveId);
  enterPlayer();
}

// What the coach says when a step BEGINS. Called on entering the player and
// on every advance — the first step of a session is a step too, and it used
// to start in silence.
function announce(st) {
  if (!st) return;
  hush();
  if (st.kind === 'prep') {
    say('get-set');
    // …then the whole set as a sentence: "Single-Leg RDL. Six reps." Queued,
    // not timed — a fixed delay landed on top of the longer names. The reps
    // come from the WORK step this prep is for, not from the prep itself.
    const work = run.queue.slice(run.idx + 1).find((q) => q.kind === 'work');
    for (const slug of setAnnounce(work)) sayAfter(slug);
  } else if (st.kind === 'rest') {
    // The engine calls the short re-brace between McGill-style reps BREATHE.
    if (st.phase === 'SWITCH SIDES') say('switch-sides');
    else if (st.phase === 'BREATHE') say('breathe');
    else say('rest');
  } else if (st.kind === 'work') {
    say('go');
  }
}

function enterPlayer() {
  view = 'player';
  lastBeat = '';
  keepAwake(true);
  // Decode everything this session will say BEFORE the first set — decoding
  // mid-beat is what makes a word land late.
  preload([
    // Exactly what this session will actually say, and nothing else. Alice's
    // vocabulary shrank twice over (cues.js) — she no longer calls the phase
    // and no longer counts the reps — so decoding the whole dictionary would
    // be dozens of clips a session that nothing will ever play.
    'get-set',
    'go',
    'rest',
    'breathe',
    'switch-sides',
    'session-complete',
    ...new Set(
      run.queue.flatMap((st) =>
        st.kind === 'work' && HOTMUM_EXERCISES[st.exId] ? setAnnounce(st) : [],
      ),
    ),
    ...new Set(
      run.queue
        .filter((st) => HOTMUM_EXERCISES[st.exId])
        .map((st) => `name-${st.exId}`),
    ),
  ]);
  renderPlayer();
  announce(step());
  tick();
}

// ─── The player ────────────────────────────────────────────────────────────

const elapsedMs = () =>
  run.elapsed + (run.running ? Date.now() - run.since : 0);

const step = () => run.queue[run.idx];

// ─── What it looks like, and what to feel ──────────────────────────────────
// The gap this closes: the player knew the name, the tempo and the seconds,
// and showed none of what a beginner actually needs — the shape of the
// movement, and the two sentences about what it should feel like and what to
// watch for. That copy has been in program.js since day one; it was only ever
// rendered on a card she'd have to go looking for, which is no use mid-set.
//
// The figure is on screen the whole time. The words are NOT: during a tempo
// set the phase word owns the screen, because reading prose while counting a
// three-second lower is not a thing anyone does. They show when she's setting
// up (prep) and when she's resting — the two moments she's looking rather
// than moving, and during a rest they describe what's COMING, not what's done.

// ─── Illustrated art, with the rig as the floor ────────────────────────────
// The SVG figure paints INSTANTLY and works offline, so it goes up first,
// every time. Then we probe /hotmum-art/<id>-a.webp (generated by
// scripts/generate-art.mjs --pack hotmum) and swap it in if it's there. Same
// two-tier contract KILOS uses: the rig is the guaranteed floor, the
// illustration is the finish, and a missing file is a slightly plainer figure
// rather than an empty panel.
//
// Two-pose art is driven by HER TEMPO rather than cross-faded on a timer: the
// working pose (-b) is held for every phase except the pattern's LAST one,
// which is always the return to the start (-a). That rule holds for every
// pattern in the program — DOWN·HOLD·UP returns on UP, UP·SQUEEZE·DOWN returns
// on DOWN, OUT·HOLD·BACK returns on BACK — so the picture moves with her.

const artCache = new Map();
const loadImg = (url) =>
  new Promise((resolve) => {
    const img = new Image();
    img.onload = () => resolve(url);
    img.onerror = () => resolve(null);
    img.src = url;
  });

function probeArt(exId) {
  if (artCache.has(exId)) return Promise.resolve(artCache.get(exId));
  const job = (async () => {
    const a = await loadImg(`/hotmum-art/${exId}-a.webp`);
    const art = a
      ? { a, b: await loadImg(`/hotmum-art/${exId}-b.webp`) }
      : null;
    artCache.set(exId, art);
    return art;
  })();
  artCache.set(
    exId,
    job.then((v) => v),
  );
  return job;
}

/** Paint the figure for `exId` into the demo element, art if we have it. */
function paintDemo(exId) {
  const el = app.querySelector('#demo');
  if (!el || !exId) return;
  const art = artCache.get(exId);
  if (art && !(art instanceof Promise)) {
    el.innerHTML = `<div class="hm-art">
      <img class="hm-art-img a on" src="${esc(art.a)}" alt="">
      ${art.b ? `<img class="hm-art-img b" src="${esc(art.b)}" alt="">` : ''}
    </div>`;
    return;
  }
  el.innerHTML = demoFor(exId);
  freezeDemoIfAsked();
  probeArt(exId).then((found) => {
    // Only swap if she's still looking at this movement.
    if (found && view === 'player' && teachingId(step(), run.idx) === exId)
      paintDemo(exId);
  });
}

/** The last phase of a tempo pattern is always the return to the start pose. */
const atWorkingPose = (tempo, label) =>
  label !== tempo.pattern[tempo.pattern.length - 1][0];

// ─── The hero says HOW MUCH, never how much is left ────────────────────────
// It has been three things. A 168px countdown of the set (a deadline — it made
// her watch a clock instead of move), then a live rep counter (2/6, still a
// thing ticking at her), and now just the dose: "6 REPS", "30 SEC". It states
// the job and then holds still.
//
// Nothing is lost. Where she is inside the set is the pip row, which fills a
// bar per rep, and the three tones at the end say when it's over — which is
// the only part of a countdown she actually needed.
function heroDose(st) {
  if (st.tempo?.reps) return `${st.tempo.reps}<i>REPS</i>`;
  if (st.secs) return `${st.secs}<i>SEC</i>`;
  return '';
}

/** The exercise the screen should be teaching right now. */
function teachingId(st, idx) {
  if (st.kind !== 'rest') return st.exId;
  const next = run.queue.slice(idx + 1).find((q) => q.kind === 'work');
  return next?.exId || st.exId;
}

function guideFor(exId, teaching = false) {
  const ex = HOTMUM_EXERCISES[exId];
  if (!ex) return '';
  // Always RENDERED; CSS decides whether it's visible. On a phone it shows
  // only while she's setting up or resting; on a desktop the right-hand column
  // is the details panel, so it stays and just dims out of the way mid-set.
  return `
    <div class="pl-guide${teaching ? ' teaching' : ''}">
      <p class="g-row g-feel"><b>FEEL</b><span>${esc(ex.feel)}</span></p>
      <p class="g-row g-avoid"><b>AVOID</b><span>${esc(ex.avoid)}</span></p>
      ${ex.knee ? `<p class="g-row g-knee"><b>KNEE</b><span>${esc(ex.knee)}</span></p>` : ''}
    </div>`;
}

function renderPlayer() {
  const st = step();
  const ex = HOTMUM_EXERCISES[st.exId];
  const isWalk = run.kind === 'walk';
  const teach = isWalk ? null : teachingId(st, run.idx);
  // Resting is when she wants to know what's coming — a rest step's own exId
  // is the move she just finished, so ask the queue instead.
  const cue =
    st.kind === 'rest'
      ? `Next — ${nextWorkLabel(run.queue, run.idx)}`
      : st.kind === 'prep' || st.kind === 'work'
        ? ex?.cue || ''
        : '';
  const teaching = st.kind === 'prep' || st.kind === 'rest';

  // `data-stage` rather than a class: tick() rewrites className every frame to
  // drive the tempo bloom, and a class set here would be wiped on the first
  // beat. The desktop grid collapses to one column when there's no pose to
  // show (a walk, a yoga class).
  app.innerHTML = `
    <div class="screen player" id="pl" data-stage="${teach ? 'on' : 'off'}">
      <div class="bloom"></div>
      <div class="pl-top">
        <div class="ex-name">${esc(isWalk ? getMovement(run.moveId).name.toUpperCase() : exName(st.exId))}</div>
        <div class="pl-tools">
          <span class="sess-clock" id="sess" aria-label="Session time">0:00</span>
          <button class="icon-btn voice-btn${voiceOn ? '' : ' muted'}" id="pl-voice" aria-pressed="${voiceOn}" aria-label="Coach voice">♪</button>
          <button class="icon-btn" id="quit" aria-label="End session">✕</button>
        </div>
      </div>

      ${teach ? `<div class="pl-stage"><div class="hm-demo${teaching ? ' teaching' : ''}" id="demo"></div></div>` : ''}

      <div class="pl-mid">
        <div class="timer as-dose" id="timer">${heroDose(st)}</div>
        <div class="phase" id="phase">${esc(st.phase || '')}</div>
        <p class="cue" id="cue">${esc(cue)}</p>
        <span class="lbl lbl-sm" id="meta">${esc(st.meta || '')}</span>
        ${teach ? guideFor(teach, teaching) : ''}
        <div class="pips" id="pips"></div>
        <div class="strip">
          <span class="lbl lbl-sm" id="tempo-lbl"></span>
          <span class="lbl lbl-sm" id="load-lbl"></span>
        </div>
      </div>

      <div class="pl-foot">
        <div class="btn-row">
          <button class="btn btn-ghost btn-sm" id="back" aria-label="Previous step" ${run.idx === 0 ? 'disabled' : ''}>BACK</button>
          <button class="btn btn-ghost" id="pause">${run.running ? 'PAUSE' : 'RESUME'}</button>
          <button class="btn btn-ghost btn-sm" id="skip" aria-label="Skip this step">SKIP</button>
        </div>
        <div class="prog"><i id="prog" style="width:0%"></i></div>
      </div>
    </div>`;

  app.querySelector('#pause').addEventListener('click', togglePause);
  app.querySelector('#back').addEventListener('click', stepBack);
  app.querySelector('#skip').addEventListener('click', () => advance(true));
  app.querySelector('#quit').addEventListener('click', endEarly);
  // Mute WITHOUT leaving the session. The toggle used to live only on the home
  // screen, so silencing Alice mid-set meant ending the run — which is the one
  // thing the player is built never to make her do.
  app.querySelector('#pl-voice').addEventListener('click', (e) => {
    voiceOn = !voiceOn;
    setMuted(!voiceOn);
    if (!voiceOn) hush();
    profile = saveProfile({ voice: voiceOn });
    e.currentTarget.setAttribute('aria-pressed', String(voiceOn));
    e.currentTarget.classList.toggle('muted', !voiceOn);
  });
  if (teach) paintDemo(teach);
  paintStatic();
}

// Reduced motion freezes every figure at its working position (each pose is
// drawn contracted for exactly this reason) — same contract as KILOS.
function freezeDemoIfAsked() {
  if (!window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches) return;
  for (const a of app.querySelectorAll('#demo animate, #demo animateTransform'))
    a.remove();
}

function paintStatic() {
  const st = step();
  const blk = st.tempo;
  const tempoLbl = app.querySelector('#tempo-lbl');
  const loadLbl = app.querySelector('#load-lbl');
  freezeDemoIfAsked();
  if (tempoLbl)
    tempoLbl.textContent = blk
      ? `TEMPO ${blk.pattern.map(([, s]) => s).join('-')}`
      : '';
  if (loadLbl) {
    const b = findBlock(st);
    loadLbl.textContent = b?.load
      ? formatLoad(b.load, profile.unit).toUpperCase()
      : '';
  }
  const pips = app.querySelector('#pips');
  if (pips) {
    pips.innerHTML = blk
      ? Array.from({ length: blk.reps }, () => '<i class="pip"></i>').join('')
      : '';
  }
}

// The block a step came from — the engine tags steps with `bi`.
function findBlock(st) {
  if (run.kind !== 'session' || st.bi == null) return null;
  return runSession().blocks[st.bi] || null;
}

function tick() {
  cancelAnimationFrame(raf);
  const frame = () => {
    if (view !== 'player' || !run) return;
    const st = step();
    const e = elapsedMs();
    const total = (st.secs ?? 0) * 1000;

    // THE ONLY CLOCK IS THE SMALL ONE UP TOP. It counts UP across the whole
    // session — completed steps plus wherever she is in this one, so a pause
    // doesn't inflate it.
    const sess = app.querySelector('#sess');
    if (sess) sess.textContent = mmss(run.totals.secs + e / 1000);

    // THE 3-2-1, as three tones. Every step, not just holds — with no
    // countdown on screen any more this is how she knows a set is ending.
    // Keyed on the step index AND the second so a re-render can't double-fire.
    if (st.secs != null) {
      const n = Math.ceil((total - e) / 1000);
      const key = `${run.idx}:${n}`;
      if (key !== lastBeat) {
        lastBeat = key;
        const tone = countdownTone(n);
        if (tone && voiceOn) beep(tone);
      }
    }

    const pl = app.querySelector('#pl');
    if (st.tempo) {
      const ts = tempoStateAt(st.tempo, e);
      const phase = app.querySelector('#phase');
      if (phase) phase.textContent = ts.label;
      const meta = app.querySelector('#meta');
      if (meta) meta.textContent = st.meta || '';
      if (pl) pl.className = `screen player ${ts.label.toLowerCase()}`;
      const stage = app.querySelector('#demo .hm-art');
      if (stage)
        stage.classList.toggle('at-b', atWorkingPose(st.tempo, ts.label));
      for (const [i, p] of [...app.querySelectorAll('.pip')].entries()) {
        p.className = `pip${i < ts.rep - 1 ? ' on' : i === ts.rep - 1 ? ' now' : ''}`;
      }
      // Nothing is spoken inside a set — the whole set was announced at
      // the top and the rep counter on screen is the running total.
    } else {
      if (pl)
        pl.className = `screen player${st.kind === 'rest' ? ' resting' : ''}`;
    }

    const prog = app.querySelector('#prog');
    if (prog)
      prog.style.width = `${((run.idx + e / (total || 1)) / run.queue.length) * 100}%`;

    if (Date.now() - lastSave > 2000) save();
    if (st.secs != null && e >= total) advance();
    else raf = requestAnimationFrame(frame);
  };
  raf = requestAnimationFrame(frame);
}

function advance(skipped = false) {
  const st = step();
  const delta = { sets: 0, tut: 0, secs: Math.round(elapsedMs() / 1000) };
  if (st.kind === 'work') {
    if (st.countsAsSet) delta.sets = 1;
    if (!skipped) delta.tut = st.secs || 0;
  }
  run.totals.sets += delta.sets;
  run.totals.tut += delta.tut;
  run.totals.secs += delta.secs;
  if (!run.deltas) run.deltas = [];
  run.deltas.push(delta);

  run.idx++;
  run.elapsed = 0;
  run.since = Date.now();
  lastBeat = '';

  if (run.idx >= run.queue.length) return finishRun();

  announce(step());

  save();
  renderPlayer();
  tick();
}

// ─── Finishing ─────────────────────────────────────────────────────────────

/** The ✕ asks first — a mis-tap mid-set shouldn't end twenty minutes of work. */
function endEarly() {
  const sets = run.totals.sets;
  // Pause the clock while she decides; the dialog shouldn't cost her seconds.
  const wasRunning = run.running;
  if (wasRunning) togglePause();

  const quit = () => {
    drop(K.active);
    run = null;
    view = 'home';
    keepAwake(false);
    cancelAnimationFrame(raf);
    renderHome();
  };

  const sheet = document.createElement('div');
  sheet.className = 'sheet';
  sheet.innerHTML = `<div class="sheet-card" role="dialog" aria-label="End the session">
      <div class="sheet-top"><h3>${sets ? 'Done for today?' : 'Leave this session?'}</h3></div>
      <p class="row-s">${
        sets
          ? `You've done ${sets} set${sets === 1 ? '' : 's'}. Finish here and they're saved — it still counts as a session.`
          : "Nothing's been logged yet, so there's nothing to save."
      }</p>
      <button class="btn" id="q-stay">KEEP GOING</button>
      <div class="btn-row">
        ${sets ? '<button class="btn btn-ghost btn-sm" id="q-finish">FINISH &amp; SAVE</button>' : ''}
        <button class="btn btn-ghost btn-sm" id="q-quit">${sets ? 'DISCARD' : 'LEAVE'}</button>
      </div>
    </div>`;
  document.body.appendChild(sheet);

  const close = () => {
    sheet.remove();
    if (wasRunning && run && !run.running) togglePause(); // pick the clock back up
  };
  sheet.querySelector('#q-stay').addEventListener('click', close);
  sheet.querySelector('#q-finish')?.addEventListener('click', () => {
    sheet.remove();
    finishRun();
  });
  sheet.querySelector('#q-quit').addEventListener('click', () => {
    sheet.remove();
    quit();
  });
  sheet.addEventListener('click', (e) => {
    if (e.target === sheet) close();
  });
}

function finishRun() {
  cancelAnimationFrame(raf);
  keepAwake(false);
  say('session-complete');
  const rec = {
    kind: run.kind,
    sessionId: run.sessionId,
    moveId: run.moveId,
    secs: run.totals.secs,
    sets: run.totals.sets,
    tut: run.totals.tut,
  };
  logDone(rec);
  drop(K.active);
  const done = { ...rec };
  run = null;
  renderFinish(done);
}

function logDone(rec) {
  const list = history();
  list.push({ date: todayKey(), at: Date.now(), ...rec });
  set(K.history, list.slice(-400));
  queuePush(); // fire-and-forget; the loop never waits on the network
}

function renderFinish(rec) {
  view = 'finish';
  const day = dayNumber();
  const isWalk = rec.kind === 'walk';
  const move = isWalk ? getMovement(rec.moveId) : null;
  const session = rec.sessionId ? getSession(rec.sessionId) : null;
  const title = isWalk ? dayTitle(move.name) : dayTitle(session.name);

  app.innerHTML = `
    <div class="screen finish">
      <div class="top">
        <span class="lbl lbl-sm">${isWalk ? 'MOVEMENT LOGGED' : 'SESSION COMPLETE'}</span>
        <span class="lbl lbl-sm">DAY ${day} OF ${SEASON.days}</span>
      </div>
      <div class="poster-type">
        <div class="pt-row"><span>${esc(SEASON.label)}</span><u>${isWalk ? 'SHE SHOWED UP' : 'SHE LIFTED IT'}</u><span>2026</span></div>
        <div>ATTN :: ${esc(profile.name.toUpperCase())}</div>
      </div>
      <div class="hero">
        <div class="day-name">${title}</div>
      </div>
      <div class="fin-grid">
        <div class="fin-cell"><b>${mmss(rec.secs)}</b><span class="lbl lbl-sm">TIME</span></div>
        <div class="fin-cell"><b>${isWalk ? move.mins : rec.sets}</b><span class="lbl lbl-sm">${isWalk ? 'MINUTES' : 'SETS'}</span></div>
        ${
          isWalk
            ? `<div class="fin-cell"><b>${history().filter((h) => h.kind === 'walk').length}</b><span class="lbl lbl-sm">MOVEMENT DAYS</span></div>`
            : `<div class="fin-cell"><b>${mmss(rec.tut)}</b><span class="lbl lbl-sm">UNDER TENSION</span></div>`
        }
        <div class="fin-cell"><b>${daysToGo()}</b><span class="lbl lbl-sm">DAYS TO GO</span></div>
      </div>
      <div class="fin-tag">
        <div class="fin-mark">HOT<br><em>MUM</em></div>
        <span class="lbl lbl-sm">HOT AS IN STRONG</span>
      </div>
      <div class="btn-row">
        <button class="btn" id="home">DONE</button>
        <button class="btn btn-share" id="share">SHARE</button>
      </div>
    </div>`;
  app.querySelector('#home').addEventListener('click', () => {
    view = 'home';
    renderHome();
  });
  app.querySelector('#share').addEventListener('click', () => openShare(rec));
}

// ─── Pause / persist / restore ─────────────────────────────────────────────

/** Redo the step before this one — she lost her place, or wants it again. */
function stepBack() {
  if (!run || run.idx === 0) return;
  const d = run.deltas?.pop();
  if (d) {
    run.totals.sets -= d.sets;
    run.totals.tut -= d.tut;
    run.totals.secs -= d.secs;
  }
  run.idx--;
  run.elapsed = 0;
  run.since = Date.now();
  run.running = true;
  lastBeat = '';
  save();
  renderPlayer();
  announce(step());
  tick();
}

function togglePause() {
  if (run.running) {
    run.elapsed += Date.now() - run.since;
    run.running = false;
  } else {
    run.since = Date.now();
    run.running = true;
  }
  save();
  renderPlayer();
  if (run.running) tick();
}

function save() {
  if (!run) return;
  lastSave = Date.now();
  set(K.active, {
    ...run,
    queue: undefined, // rebuilt from the program on restore
    elapsed: elapsedMs(),
    since: Date.now(),
    savedAt: Date.now(),
  });
}

function restore() {
  const s = get(K.active);
  if (!s) return false;
  // Anything older than 6 hours is a forgotten session, not a paused one.
  if (Date.now() - (s.savedAt || 0) > 6 * 3600 * 1000) {
    drop(K.active);
    return false;
  }
  if (s.kind === 'walk') {
    // Build the movement run WITHOUT entering the player — startMove() would
    // enter it here and again below, announcing "go" twice and preloading twice.
    buildWalkRun(s.moveId);
    run.idx = s.idx;
    run.elapsed = s.elapsed;
    run.totals = s.totals || run.totals;
  } else {
    const session = prepped(s.sessionId, {
      easyKnee: s.easyKnee,
      day: s.day,
    });
    if (!session) {
      drop(K.active);
      return false;
    }
    run = {
      ...s,
      queue: buildStepQueue(session),
    };
    if (run.idx >= run.queue.length) {
      drop(K.active);
      return false;
    }
  }
  run.running = false; // always resume paused — she may not be holding the phone
  run.since = Date.now();
  enterPlayer();
  return true;
}

for (const ev of ['pagehide', 'visibilitychange']) {
  window.addEventListener(ev, () => {
    if (run && view === 'player') save();
  });
}
// iOS suspends the AudioContext whenever the app is backgrounded — coming back
// to a silent coach mid-session is exactly the bug this whole module exists for.
document.addEventListener('visibilitychange', () => {
  if (!document.hidden) resumeIfNeeded();
});

// Escape closes the topmost sheet. Every sheet is dismissible by tapping the
// backdrop or the ✕; on a laptop the key is what people actually reach for.
document.addEventListener('keydown', (e) => {
  if (e.key !== 'Escape') return;
  const sheets = document.querySelectorAll('.sheet');
  const top = sheets[sheets.length - 1];
  if (!top) return;
  // The quit dialog owns its own dismissal — it has to un-pause the clock.
  const stay = top.querySelector('#q-stay');
  if (stay) stay.click();
  else top.remove();
});

// ─── Boot ──────────────────────────────────────────────────────────────────

const resumed = restore();
if (!resumed) renderHome();

// Reconcile with the cloud in the background — never on the critical path.
syncOnStart().then(() => {
  if (!resumed) offerBackup(); // never interrupt a restored session
});

if (!resumed) autoApplyUpdate();

// The mock lives at /hotmum-mock.html; this is the real thing.
export { renderHome };
