// ─── TOMATO PLATE — plan + food reference ───────────────────────────────────
// Content authored from public sources (NHS OGL v3.0, CDC/USDA public domain,
// NIAID/AAAAI/ASCIA guidelines, WHO). Nothing copied from Solid Starts.
// Evidence and sourcing: subo/FEEDING.md.

export const ALLERGENS = [
  { id: 'egg', name: 'Egg' }, { id: 'peanut', name: 'Peanut' },
  { id: 'dairy', name: 'Dairy' }, { id: 'fish', name: 'Fish' },
  { id: 'wheat', name: 'Wheat' }, { id: 'soy', name: 'Soy' },
  { id: 'sesame', name: 'Sesame' }, { id: 'treenut', name: 'Tree nut' },
  { id: 'shellfish', name: 'Shellfish' },
]

export const ROTATION_DAYS = 7 // once introduced, serve at least weekly — forever
export const EXPOSURE_TARGET = 10 // most parents quit at 3–5; evidence says 8–10+

const f = (o) => ({ choking: 'low', ironMg: 0, allergen: null, prep: [], safety: '', ...o })

export const FOODS = {
  kamote: f({ name: 'Kamote', sub: 'Sweet potato', cat: 'vegetable', art: 'kamote', ironMg: 0.61,
    cut: { 6: ['Smooth purée, thinned loose', 'Not yet — spoon only'],
           9: ['Fork-mashed, visible lumps', 'Finger-length baton, two fingers wide'],
           12: ['Coarse mash', 'Soft cubes, pincer-sized'] },
    prep: ['Peel, cut into chunks about the width of your thumb.', 'Steam 12–15 min until a fork meets no resistance.',
           'Keep the cooking water.', 'Set aside a baton before you mash the rest.',
           'Mash, thinning with the cooking water.'],
    buy: 'The orange-fleshed kind if you can find it — more beta-carotene than the pale variety.',
    safety: 'Thin with the cooking water, never breastmilk on this plan. Serve lukewarm.' }),
  carrot: f({ name: 'Carrot', sub: '', cat: 'vegetable', art: 'carrot', ironMg: 0.3,
    cut: { 6: ['Smooth purée', 'Not yet'], 9: ['Fork-mashed', 'Two-finger baton, squash-tested'],
           12: ['Soft cubes', 'Small cubes he picks up'] },
    prep: ['Peel, cut into batons.', 'Steam until it squashes between your finger and thumb.',
           'Set a baton aside, blend the rest with the cooking water.'],
    safety: 'Raw carrot is a hard-food choking risk. Always cooked soft, never raw sticks.' }),
  kalabasa: f({ name: 'Kalabasa', sub: 'Squash', cat: 'vegetable', art: 'kalabasa', ironMg: 0.8,
    cut: { 6: ['Smooth purée', 'Not yet'], 9: ['Fork-mashed with lumps', 'Steamed baton'],
           12: ['Soft cubes', 'Cubes, or the family dish before salt'] },
    prep: ['Peel, cut into chunks about the width of your thumb.', 'Steam 12–15 min until very soft.',
           'Blend with the cooking water to a slow drop off the spoon.'],
    safety: '' }),
  sayote: f({ name: 'Sayote', sub: 'Chayote', cat: 'vegetable', art: 'sayote',
    cut: { 6: ['Smooth purée', 'Not yet'], 9: ['Mashed', 'Soft cubes'], 12: ['Soft cubes', 'Cubes'] },
    prep: ['Peel, boil until soft.', 'Blend smooth with the cooking water.'], safety: '' }),
  chicken: f({ name: 'Chicken', sub: 'Breast', cat: 'protein', art: 'chicken', ironMg: 1.0,
    cut: { 6: ['Blended very smooth with unsalted broth', 'Not yet'],
           9: ['Finely minced through a mash', 'Soft shreds'],
           12: ['Chopped small', 'Shredded pieces'] },
    prep: ['Boil until cooked through.', 'Blend very smooth with unsalted cooking broth.'],
    pairing: 'Chicken alone is not a strong iron source. Once malunggay or monggo are in, serve them together.',
    safety: '' }),
  avocado: f({ name: 'Avocado', sub: '', cat: 'fruit', art: 'avocado',
    cut: { 6: ['Mashed, loosened with warm water', 'Not yet'], 9: ['Mashed', 'Ripe wedges'],
           12: ['Chunks', 'Cubes'] },
    prep: ['Ripe only.', 'Mash with a fork, loosen with warm water. No cooking.'], safety: '' }),
  liver: f({ name: 'Chicken liver', sub: 'Atay ng manok', cat: 'protein', art: 'liver', ironMg: 11.6,
    maxPerWeek: 2,
    cut: { 6: ['Blended smooth into lugaw', 'Not yet'], 9: ['Finely mashed through lugaw', 'Serve a kamote stick alongside'],
           12: ['Finely chopped into rice', 'Small pieces'] },
    prep: ['Rinse, trim greenish or stringy bits.', 'Simmer 8–10 min until NO pink remains.',
           'Blend smooth with a little cooking liquid.', 'Start with a fingertip — the flavour is strong.'],
    pairing: 'Once lugaw is in the rotation this is the iron workhorse: plain lugaw is 0.45mg iron, with liver it is 10.20mg.',
    buy: 'Fresh chicken liver from the palengke or the supermarket chiller. Buy it the day you cook it.',
    safety: 'MAX TWICE A WEEK. Extremely vitamin-A dense — the one food where more is worse.' }),
  lakatan: f({ name: 'Lakatan', sub: 'Banana', cat: 'fruit', art: 'banana',
    cut: { 6: ['Mashed smooth', 'Not yet'], 9: ['Mashed', 'Spear, skin peeled halfway back to grip'],
           12: ['Chunks', 'Pieces he manages himself'] },
    prep: ['Ripe.', 'Mash with a fork, or cut lengthwise into a spear.'], safety: '' }),
  papaya: f({ name: 'Papaya', sub: '', cat: 'fruit', art: 'papaya',
    cut: { 6: ['Mashed smooth', 'Not yet'], 9: ['Mashed', 'Ripe strips'], 12: ['Cubes', 'Cubes'] },
    prep: ['Ripe, seeds removed.', 'Mash or blend smooth.'],
    safety: 'High in vitamin C — a good partner beside monggo and malunggay for absorbing plant iron.' }),
  egg: f({ name: 'Egg', sub: 'Itlog — WHOLE', cat: 'protein', art: 'egg', allergen: 'egg', ironMg: 1.19,
    cut: { 6: ['Mashed fine, loosened', 'Not yet'], 9: ['Mashed', 'Omelette cut into finger strips'],
           12: ['Chopped', 'Wedges, omelette fingers'] },
    prep: ['Hard-boil AT LEAST 10 minutes from boiling.', 'Mash the YOLK AND THE WHITE together.',
           'Loosen with cooking water or a familiar purée.'],
    buy: 'Any fresh egg. The WHOLE egg — yolk and white together.',
    safety: 'WELL-COOKED ONLY. Yolk alone does not introduce egg — the proteins people react to are in the white. Never raw, runny, or raw-pasteurised egg powder.' }),
  peanut: f({ name: 'Peanut', sub: 'Mani', cat: 'protein', art: 'peanut', allergen: 'peanut', choking: 'high',
    cut: { 6: ['2 tsp peanut butter thinned into a purée', 'Never as finger food'],
           9: ['Thinned through porridge', 'Never a lump'],
           12: ['A thin scrape on toast', 'Thin scrape only'] },
    prep: ['Two thumb-sized scoops of smooth peanut butter in a small bowl.', 'Add about the same again in HOT water, stir to a loose pourable cream.',
           'Cool it.', 'Stir through a few thumb-sized spoonfuls of a purée he already likes.'],
    buy: "Peanut butter with 100% peanuts on the label and nothing else. Most standard supermarket brands add sugar AND salt — look for 'natural' or grind-your-own, and read the panel, not the front.",
    safety: 'NEVER off a spoon, NEVER a lump. No whole or chopped nuts before age 4. Thick nut butter is a real airway risk.' }),
  malunggay: f({ name: 'Malunggay', sub: 'Moringa', cat: 'vegetable', art: 'malunggay', ironMg: 4.0,
    cut: { 6: ['Blended INTO another purée — never alone', 'Not yet'],
           9: ['Finely chopped through food', 'Not as finger food'],
           12: ['Cooked into family dishes', '—'] },
    prep: ['Strip leaves off the stems completely — stems stay fibrous.', 'Boil 3–5 min until fully wilted.',
           'Blend VERY smooth.', 'Stir a spoonful into a purée he already has — never served on its own.'],
    pairing: 'Its own vitamin C helps absorb its iron, so it pairs well with dilis or monggo.',
    safety: 'Carries its own vitamin C, so it helps absorb its own iron. Pairs naturally with dilis.' }),
  tilapia: f({ name: 'Tilapia', sub: '', cat: 'protein', art: 'fish', allergen: 'fish', choking: 'moderate',
    cut: { 6: ['Mashed into lugaw', 'Not yet'], 9: ['Flaked into soft lumps', 'Large soft flakes'],
           12: ['Flaked into family dishes', 'Flakes'] },
    prep: ['Steam or poach 8–10 min until it flakes.', 'DEBONE METICULOUSLY — flake apart by hand and check twice.',
           'Mash with the cooking water.'],
    safety: 'Bones. Check by hand, twice, every time.' }),
  beef: f({ name: 'Beef', sub: 'Lean ground', cat: 'protein', art: 'meat', ironMg: 2.6,
    cut: { 6: ['Blended very smooth with broth', 'Not yet'], 9: ['Finely minced', 'Flattened soft patty'],
           12: ['Small pieces', 'Flattened patty — never a ball'] },
    prep: ['Simmer in a little water, breaking it up, 8–10 min.',
           'Blend with the cooking liquid — it stays gritty otherwise.'],
    safety: 'Never roll round meatballs. Round firm shapes are a choking hazard — flatten them.' }),
  yogurt: f({ name: 'Plain yogurt', sub: '', cat: 'dairy', art: 'yogurt', allergen: 'dairy',
    cut: { 6: ['Plain, spoon-fed', 'Not yet'], 9: ['With mashed fruit', '—'], 12: ['As is', '—'] },
    prep: ['Plain, full-fat, unsweetened only.', 'Stir in fruit purée if he needs it sweeter — never sugar or honey.'],
    buy: "Plain, unsweetened, full-fat. Most yogurt sold here is sweetened, including the 'plain-looking' tubs — read the label. Greek-style plain works well.",
    safety: 'Yogurt and cheese are fine now. Liquid cow’s milk as a DRINK is not, before 12 months — low iron, and gut blood loss in infants.' }),
  oats: f({ name: 'Oats', sub: '', cat: 'grain', art: 'oats',
    cut: { 6: ['Ground, cooked soft with water', 'Not yet'], 9: ['As cooked, thicker', 'Toast fingers alongside'],
           12: ['Family porridge', 'Oat pancake strips'] },
    prep: ['Grind oats, cook soft with water.', 'Alternate with rice — rice takes up ~10x more arsenic than other grains.'],
    buy: 'Plain rolled or quick oats — Quaker is on every shelf here. NOT the flavoured instant sachets: they carry a lot of added sugar.',
    safety: '' }),
  wheat: f({ name: 'Pasta / bread', sub: 'Wheat', cat: 'grain', art: 'pasta', allergen: 'wheat',
    cut: { 6: ['Overcooked and mashed', 'Not yet'], 9: ['Soft pieces', 'Soft pasta — a top finger food'],
           12: ['Family pasta cut small', 'Pieces'] },
    prep: ['Boil small pasta well PAST the packet time.', 'Mash, or serve whole soft pieces.',
           'Or soak a bread strip soft.'],
    buy: 'Small pasta shapes — elbow, stelline, or anything tiny. Plain bread, no added sugar.',
    safety: 'No salt in the cooking water.' }),
  pork: f({ name: 'Pork', sub: 'Lean ground', cat: 'protein', art: 'meat', ironMg: 1.0,
    cut: { 6: ['Blended smooth with broth', 'Not yet'], 9: ['Finely minced', 'Flattened soft piece'],
           12: ['Small pieces', 'Flattened, never a ball'] },
    prep: ['Simmer through, breaking it up.', 'Blend smooth with the cooking liquid.'],
    safety: 'Flatten, never roll into balls.' }),
  tofu: f({ name: 'Tofu / taho', sub: 'Tokwa', cat: 'protein', art: 'tofu', allergen: 'soy', ironMg: 2.66,
    cut: { 6: ['Mashed smooth', 'Not yet'], 9: ['Mashed', 'Soft cubes — one of the best finger foods'],
           12: ['Cubed into family dishes', 'Cubes'] },
    prep: ['Soft or silken tofu, or plain taho with NO arnibal.', 'Mash with a fork — no cooking needed for silken.'],
    buy: 'Silken or soft tofu from the chiller, or tokwa from the wet market. Taho from a vendor is fine if you skip the arnibal entirely.',
    safety: 'NOT soy sauce for the soy introduction — toyo has almost no protein and an enormous salt load.' }),
  dilis: f({ name: 'Dilis', sub: 'Fresh anchovy', cat: 'protein', art: 'fish', allergen: 'fish',
    ironMg: 3.25, choking: 'moderate',
    cut: { 6: ['Mashed completely smooth into lugaw', 'Not yet'], 9: ['Finely flaked', 'Serve a kalabasa baton alongside'],
           12: ['Flaked into family dishes', 'Flakes'] },
    prep: ['FRESH dilis only — never dried salted.', 'Heads and guts out; debone by running a thumb down the spine.',
           'Simmer 5–8 min until it flakes.', 'CHECK FOR BONES AGAIN, by hand.', 'Mash completely smooth.'],
    pairing: 'Dilis and malunggay in lugaw is the cheapest iron meal in the plan.',
    buy: 'FRESH dilis from the palengke, not the dried salted snack kind — that one is far too much salt for a baby.',
    safety: 'About 10x the iron of bangus, plus real calcium, and on the FDA low-mercury list. Never the dried salted kind — far too much salt.' }),
  tahini: f({ name: 'Tahini', sub: 'Sesame paste', cat: 'protein', art: 'tahini', allergen: 'sesame',
    choking: 'high', ironMg: 8.95,
    cut: { 6: ['1 tsp thinned into a purée', 'Never as finger food'], 9: ['Thinned through porridge', 'Never a lump'],
           12: ['Thinly spread', 'Hummus with soft veg sticks'] },
    prep: ['Thin a fingertip of tahini with warm water to a loose cream.', 'Stir through a familiar purée.'],
    buy: 'Plain sesame paste, no sugar. Specialty aisle — Healthy Options, S&R or Landers usually carry it. Hummus works too.',
    safety: 'Same rule as peanut — thick paste must be thinned, never a lump. No sesame candy or brittle.' }),
  cashew: f({ name: 'Cashew butter', sub: 'Kasuy', cat: 'protein', art: 'nut', allergen: 'treenut',
    choking: 'high', ironMg: 5.16,
    cut: { 6: ['Thinned into a purée', 'Never as finger food'], 9: ['Thinned through porridge', 'Never a lump'],
           12: ['A thin scrape on toast', 'Thin scrape'] },
    prep: ['Thin a fingertip or two of smooth cashew butter with hot water.', 'Cool, then stir through a familiar purée.'],
    buy: 'Smooth cashew butter, 100% nuts. Specialty aisle or online; check for no added sugar or salt.',
    safety: 'NO whole or chopped tree nuts before age 4. Nut butter only, and thinned.' }),
  shrimp: f({ name: 'Shrimp', sub: 'Hipon', cat: 'protein', art: 'shrimp', allergen: 'shellfish',
    choking: 'moderate',
    cut: { 6: ['Puréed or chopped very fine', 'Not yet'], 9: ['Finely chopped — never rings', 'Not yet'],
           12: ['Chopped small', 'Tiny pieces only'] },
    prep: ['Cook until opaque all the way through, 3–4 min.', 'Shell completely and devein.',
           'Chop VERY fine or blend.'],
    buy: 'Fresh or frozen, shelled or unshelled. Small ones are easier to chop fine.',
    safety: 'Rubbery and hard for a baby to break down — go finer than feels necessary.' }),
  monggo: f({ name: 'Monggo', sub: 'Mung beans', cat: 'legume', art: 'monggo', ironMg: 1.4,
    cut: { 6: ['Blended smooth', 'Not yet'], 9: ['Mashed — a good early lumpy texture', 'Whole soft beans'],
           12: ['Family monggo with malunggay', 'Whole beans'] },
    prep: ['SOAK OVERNIGHT, drain, rinse.', 'Boil 30–40 min until the beans collapse.',
           'Blend smooth with the cooking water.'],
    pairing: 'Serve beside something with vitamin C — papaya, or a squeeze of calamansi — to absorb the plant iron.',
    buy: 'Dry monggo from any palengke or supermarket. Soak it overnight before cooking.',
    safety: 'Soaking overnight cuts phytate about 45%, which meaningfully improves iron and zinc absorption. Free win.' }),
  mangga: f({ name: 'Mangga', sub: 'Mango', cat: 'fruit', art: 'mango',
    cut: { 6: ['Mashed smooth', 'Not yet'], 9: ['Soft strips', 'Strips he can hold'], 12: ['Cubes', 'Cubes'] },
    prep: ['Ripe only.', 'Mash, or cut into soft strips.'], safety: '' }),
  bangus: f({ name: 'Bangus', sub: 'Milkfish', cat: 'protein', art: 'fish', allergen: 'fish',
    ironMg: 0.32, choking: 'high',
    cut: { 6: ['Mashed into lugaw', 'Not yet'], 9: ['Flaked into soft lumps', 'Large soft flakes'],
           12: ['Flaked into family dishes', 'Flakes'] },
    prep: ['Steam 8–10 min until it flakes.', 'DEBONE METICULOUSLY — bangus is notoriously bony. Check twice.',
           'Mash with the cooking water.'],
    buy: "Boneless bangus belly saves a lot of deboning, but still check by hand — 'boneless' is never a guarantee.",
    safety: 'Good food, but a poor iron source at 0.32mg. Use dilis or liver for iron.' }),
  lugaw: f({ name: 'Lugaw', sub: 'Rice porridge', cat: 'grain', art: 'lugaw', ironMg: 0.45,
    cut: { 6: ['Blended smooth', 'Not yet'], 9: ['As cooked, with soft lumps', 'Toast fingers alongside'],
           12: ['Family lugaw before salt', '—'] },
    prep: ['Rinse, simmer 25–30 min until the grains collapse.', 'Cook it THICK — it should mound on a spoon.',
           'Something from the iron list goes in every time.'],
    buy: 'Any white rice. Rotate it with oats — rice takes up roughly 10x more arsenic than other grains.',
    safety: 'The base, never the meal. On its own it is 0.45mg iron; with chicken liver it is 10.20mg — about 23x.' }),
}

// ── The plan ────────────────────────────────────────────────────────────────
// Months 6–7 (+ the last 3 allergens): one new ingredient every 3 days.
const T = (food, note = '') => ({ food, note })
export const TRIALS = {
  6: [T('kamote'), T('carrot'), T('kalabasa'), T('sayote'), T('chicken', 'First animal protein'),
      T('avocado'), T('liver', 'Iron starts here'), T('lakatan'), T('papaya', 'First fruit'),
      T('egg', 'Whole egg — yolk and white')],
  7: [T('peanut', 'Strongest evidence of any allergen'), T('malunggay'), T('tilapia'), T('beef'),
      T('yogurt'), T('oats'), T('wheat'), T('pork'), T('tofu'), T('dilis')],
  8: [T('tahini'), T('cashew'), T('shrimp')],
}

// From month 8 day 10 — a 7-day cycle that repeats, on purpose.
// Every allergen comes round at least weekly; liver lands exactly twice.
export const CYCLE = [
  { id: 'A', meals: {
      breakfast: { spoon: 'Oat lugaw with thinned peanut butter + mashed lakatan', hands: 'Lakatan spear', foods: ['oats', 'peanut', 'lakatan'] },
      lunch: { spoon: 'Chicken + kalabasa + soft rice', hands: 'Kalabasa baton', foods: ['chicken', 'kalabasa'] },
      dinner: { spoon: 'Chicken liver lugaw with malunggay', hands: 'Kamote stick', foods: ['liver', 'malunggay', 'lugaw'] } },
    snack: 'Papaya cubes', iron: 'Liver — 1 of 2 this week' },
  { id: 'B', meals: {
      breakfast: { spoon: 'Plain yogurt with papaya mash', hands: 'Papaya strips', foods: ['yogurt', 'papaya'] },
      lunch: { spoon: 'Dilis + malunggay lugaw', hands: 'Soft toast fingers', foods: ['dilis', 'malunggay', 'wheat'] },
      dinner: { spoon: 'Beef + carrot mash', hands: 'Two-finger carrot baton', foods: ['beef', 'carrot'] } },
    snack: 'Avocado slices', iron: 'Dilis + beef' },
  { id: 'C', meals: {
      breakfast: { spoon: 'Whole egg mashed with avocado', hands: 'Omelette finger strips', foods: ['egg', 'avocado'] },
      lunch: { spoon: 'Pork mince + kamote', hands: 'Kamote cubes', foods: ['pork', 'kamote'] },
      dinner: { spoon: 'Tilapia + sayote mash', hands: 'Soft sayote cubes', foods: ['tilapia', 'sayote'] } },
    snack: 'Mango wedges', iron: 'Egg + fish' },
  { id: 'D', meals: {
      breakfast: { spoon: 'Oat lugaw + tahini thinned + mango', hands: 'Toast strips', foods: ['oats', 'tahini', 'mangga', 'wheat'] },
      lunch: { spoon: 'Chicken + sayote + soft rice', hands: 'Steamed sayote sticks', foods: ['chicken', 'sayote'] },
      dinner: { spoon: 'Tofu + kalabasa mash with malunggay', hands: 'Soft tofu cubes', foods: ['tofu', 'kalabasa', 'malunggay'] } },
    snack: 'Plain yogurt with banana', iron: 'Tofu + malunggay' },
  { id: 'E', meals: {
      breakfast: { spoon: 'Plain yogurt with avocado mash', hands: 'Ripe banana spear', foods: ['yogurt', 'avocado', 'lakatan'] },
      lunch: { spoon: 'Bangus flaked + carrot + rice', hands: 'Carrot batons', foods: ['bangus', 'carrot'] },
      dinner: { spoon: 'Chicken liver lugaw with kamote', hands: 'Steamed kalabasa baton', foods: ['liver', 'kamote', 'lugaw'] } },
    snack: 'Kalabasa cubes', iron: 'Liver — 2 of 2, stop here this week' },
  { id: 'F', meals: {
      breakfast: { spoon: 'Oat lugaw + cashew butter thinned + lakatan', hands: 'Lakatan spear', foods: ['oats', 'cashew', 'lakatan'] },
      lunch: { spoon: 'Beef + monggo + soft rice', hands: 'Soft beef, flattened', foods: ['beef', 'monggo'] },
      dinner: { spoon: 'Shrimp chopped very fine + monggo + kamote', hands: 'Kamote sticks', foods: ['shrimp', 'monggo', 'kamote'] } },
    snack: 'Papaya cubes', iron: 'Monggo — soak overnight' },
  { id: 'G', meals: {
      breakfast: { spoon: 'Egg scrambled soft + toast strips', hands: 'Toast fingers', foods: ['egg', 'wheat'] },
      lunch: { spoon: 'Tilapia + kalabasa + lugaw', hands: 'Kalabasa cubes', foods: ['tilapia', 'kalabasa', 'lugaw'] },
      dinner: { spoon: 'Ground pork + sayote + malunggay', hands: 'Soft pork, flattened small', foods: ['pork', 'sayote', 'malunggay'] } },
    snack: 'Mango wedges', iron: 'Pork + malunggay' },
]

// Milk taper — the wean runs to 12 months (see subo/ Milk & weaning).
export const MILK = [
  { m: 6, feeds: 5, meals: 1, note: 'Solids AFTER a milk feed. Milk is still all his nutrition.' },
  { m: 7, feeds: 5, meals: 1, note: 'Moving to 2 meals by the end of the month.' },
  { m: 8, feeds: 5, meals: 2, note: 'Appetite becomes real. Iron from food starts mattering.' },
  { m: 9, feeds: 5, meals: 2, note: 'Start offering SOLIDS FIRST at one meal — that is the wean mechanism.' },
  { m: 10, feeds: 4, meals: 3, note: 'Drop the 10am feed; it becomes the 10am snack.' },
  { m: 11, feeds: 3, meals: 3, note: 'Drop the 3pm feed. Solids first at every meal.' },
  { m: 12, feeds: 2, meals: 3, note: 'Drop the noon feed, then the morning. Bedtime goes last.' },
]

// How much to OFFER (never a target to finish) — keyed by day of the plan.
export const AMOUNTS = [
  { upTo: 21, offer: 'A fingertip’s worth, building to a thumb-sized spoonful', meals: '1 meal a day, after a milk feed' },
  { upTo: 42, offer: 'Two or three thumb-sized spoonfuls', meals: '1 meal, moving to 2' },
  { upTo: 63, offer: 'Three or four thumb-sized spoonfuls — about half his cupped palm', meals: '2 meals a day' },
  { upTo: 1e4, offer: 'Roughly his own cupped palm, per meal', meals: '3 meals + a snack' },
]

// No rulers, no measuring spoons — everything sized against a hand.
// What he ate, relative to what you offered — not abstract sizes.
export const TAKEN = [
  { id: 'none', label: 'None', desc: 'Turned away, or spat it out' },
  { id: 'taste', label: 'A taste', desc: 'A spoon or two' },
  { id: 'half', label: 'About half', desc: 'Half of what you offered' },
  { id: 'all', label: 'All of it', desc: 'Finished, or wanted more' },
]

export const HAND_GUIDE = [
  ['A fingertip', 'Roughly a teaspoon. The starting amount, and the dose for strong things like liver or nut butter.'],
  ['Your thumb', 'Tip to the first knuckle is roughly a tablespoon — the everyday spoonful.'],
  ['Thumb-width', 'How big to cut chunks before steaming. Thicker cooks unevenly.'],
  ['Your index finger', 'The length of a baton for him to hold — long enough that a good bit sticks out of his fist.'],
  ['Two fingers', 'How WIDE a baton should be. Thinner than that and he cannot grip it.'],
  ['His cupped palm', 'About one full meal by the end of the first year.'],
  ['Finger and thumb', 'The squash test — every piece must crush with light pressure. If it will not, cook it longer.'],
]

export const REACTION = {
  urgent: ['Lip, face or tongue swelling', 'Widespread hives', 'Vomiting', 'Difficulty breathing or wheeze',
    'Repetitive cough', 'Colour change — pale or blue', 'Sudden lethargy or floppiness'],
  mild: ['A new rash', 'A few hives around the mouth or face'],
  notReaction: 'A mild rash ONLY around the mouth, with no other symptoms, is very often just contact irritation from acidic food — offer the food again. Gagging or coughing on a new texture is a texture problem, not an immune one. Check with the pediatrician before removing any food: it is much easier to keep a food in than to get it back.',
}
